### ISSUE TITLE
Update with version 2.1 causes error

### ISSUE THREAD

**Issue by mattgig** [lmsace/moodle-hide-correct-questions#5]
When you try to install the version v2.1 (2024041200), you'll get an error: "Coding error detected, it must be fixed by a programmer: Incorrect syntax in plugin supported declaration in hidecorrect". And the plugin update routine goes into an endless loop.

Here is the stack trace:
line 309 of /lib/classes/plugininfo/base.php: coding_exception thrown
line 199 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 150 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 398 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 358 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1193 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1314 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 205 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 710 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

To fix the problem for the moment, either deinstall the plugin from your server are use the older version of the plugin (remember to adjust the version number).

**Comment by prasanna-lmsace** [comment]
Hi @mattgig,

Thank you for bringing this issue to our attention. We have fixed the installation issue and released a new version.

Thanks, 
Prasanna
